framework:
    messenger:
        transports:
            sync: 'sync://'

        default_bus: command.bus
        buses:
            command.bus: ~
            event.bus:
                default_middleware: allow_no_handlers
            integration.event.bus: ~
